steps:
- name: 'maven:3.3-jdk-8'
  entrypoint: 'mvn'
  args: ['test', 'install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gauge-controller', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gauge-controller']
