steps:
- name: 'maven:3.3-jdk-8'
  args: ['run', '-it', '--rm', '--name my-maven-project', '-v', "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven", 'clean', 'install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/[SERVICE-NAME]', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/[SERVICE-NAME]']
  # Deploy container image to Cloud Run
