steps:
  - name: 'golang'
    entrypoint: 'git'
    args: [ 'config', '--global', '--add', 'safe.directory', '/workspace' ]

  - name: 'golang'
    entrypoint: 'go'
    args: [ 'get', '-d', '-t', '-v', './...' ]
  - name: 'golang'
    entrypoint: 'go'
    args: [ 'install', '-v', './...' ]

  - name: 'golang'
    entrypoint: 'go'
    args: [ 'build', '-v' ]
  - name: 'golang'
    entrypoint: 'go'
    args: [ 'test', './...' ]

  - name: 'node:21-alpine'
    entrypoint: 'npm'
    dir: 'client'
    args: [ 'install' ]
  - name: 'node:21-alpine'
    entrypoint: 'npm'
    dir: 'client'
    args: [ 'run', 'build' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/gauge-controller', '.' ]

images:
  - 'eu.gcr.io/$PROJECT_ID/gauge-controller'
