apiVersion: v1
kind: Service
metadata:
  name: gauge-controller
spec:
  type: NodePort
  selector:
    app: gauge-controller
  ports:
  - port: 8080
    name: gauge-controller
    nodePort: 32100
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gauge-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gauge-controller
    spec:
      containers:
      - name: gauge-controller
        image: localhost:5000/gauge-controller:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /opt/conf
      volumes:
      - name: config-volume
        configMap:
          name: gauge-controller-config
